spring:
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.chamberlain: DEBUG
    org.testcontainers: INFO

chamberlain:
  cache:
    enabled: false

