// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/scenes","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"场景管理","path":"/scenes","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"配置管理","path":"/configs","parentId":"ant-design-pro-layout","id":"3"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Scenes__index" */'@/pages/Scenes/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Configs__index" */'@/pages/Configs/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/duguguiyu-work/workspace/chamberlain/examples/demo-app/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
