spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://mysql:3306/chamberlain?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:chamberlain}
    password: ${MYSQL_PASSWORD}
  
  # 生产环境使用 Flyway 管理数据库迁移
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true  # 生产环境禁止清理数据库
    out-of-order: false
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # 生产环境必须使用 validate
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 3000ms

logging:
  level:
    root: WARN
    com.chamberlain: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/chamberlain.log
    max-size: 100MB
    max-history: 30

chamberlain:
  cache:
    enabled: true  # 生产环境启用缓存

