spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chamberlain_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
  
  # 开发环境使用 Flyway 管理数据库
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false  # 开发环境允许清理数据库
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  # 使用 validate 而不是 update，确保与 Flyway 脚本一致
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

logging:
  level:
    root: INFO
    com.chamberlain: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

chamberlain:
  cache:
    enabled: false  # 开发环境禁用缓存，便于调试

