spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chamberlain_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.chamberlain: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

chamberlain:
  cache:
    enabled: false  # 开发环境禁用缓存

